# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:            Sampath Vanimisetti
subtitle:         Weblog for the 2017 Udacity Self-Driving Car Nanodegree
description:      This site is a detailed log of my experience during Udacity's self-driving car nanodegree. The idea is to share information to help upcoming student cohorts.
keywords:         udacity self-driving autonomous vehicle car
language:         "en" # default language of the blog. Language codes: http://www.w3schools.com/tags/ref_language_codes.asp

baseurl:          "/USDCND17" # the subpath of your site, e.g. /blog
url:              "https://svanimisetti.in" # the base hostname & protocol for your site. Have a look at robots.txt as well!
permalink:        /blog/:categories/:title
cover:            /assets/mountain-cover.jpg
disqus_shortname: "usdcnd17"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
